version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: cmd/Dockerfile
    restart: unless-stopped
    volumes:
      - ./config.json:/opt/bot/config.json:ro
      - ./data:/opt/bot/data
    command: --sync-commands=true
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=false" # Change to true & add router rules if you expose HTTP endpoints later

networks:
  dokploy-network:
    external: true